app:
    mode: dev
    port: 8080
    tls:
        status: off
        pemPath: cert/server.pem
        keyPath: cert/server.key

broker:
    # native or redis
    driver: native

redis:
    addr: localhost:6379
    password:
    db: 0
    channel: rabbit

log:
    level: debug
    output: stdout
    format: json

releases:
    path: /app/var/releases

build:
    path: /app/var/build