app:
    mode: dev
    port: 8080
    tls:
        status: off
        pemPath: cert/server.pem
        keyPath: cert/server.key

broker:
    # native or redis
    driver: native
    # Native Driver Configs
    native:
        capacity: 50
        workers: 1
    # Redis Configs
    redis:
        addr: localhost:6379
        password:
        db: 0
        channel: rabbit


log:
    level: debug
    output: stdout
    format: json

releases:
    path: /app/var/releases

build:
    path: /app/var/build