# General App Configs
app:
    # Env mode (dev or prod)
    mode: prod
    # HTTP port
    port: ${RABBIT_LISTEN_PORT:-8080}
    # App URL
    domain: ${RABBIT_DOMAIN:-http://localhost:8080}
    # TLS configs
    tls:
        status: ${RABBIT_TLS_STATUS:-off}
        pemPath: ${RABBIT_TLS_CERT:-cert/server.pem}
        keyPath: ${RABBIT_TLS_CERTKEY:-cert/server.key}

# Redis Configs
redis:
    addr: ${RABBIT_REDIS_ADDR:-redis:6379}
    password: ${RABBIT_REDIS_PASSWORD}
    db: ${RABBIT_REDIS_DB:-0}

# Message Broker Configs
broker:
    # Broker driver (native or redis)
    driver: native
    # Native driver configs
    native:
        # Queue max capacity
        capacity: 50
        # Number of concurrent workers
        workers: 1
    # Redis Driver Configs
    redis:
        channel: rabbit

# Log configs
log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${RABBIT_LOG_LEVEL:-warn}
    # output can be stdout or abs path to log file /var/logs/rabbit.log
    output: ${RABBIT_LOG_OUTPUT:-stdout}
    # Format can be json or text
    format: json

# Release configs
releases:
    # Releases absolute path
    path: ${RABBIT_RELEASES_PATH:-/app/var/releases}
    name: "[.Tag]"

# Build configs
build:
    # Build absolute path
    path: ${RABBIT_BUILD_PATH:-/app/var/build}
    # Number of parallel builds
    parallelism: 1

# Application Database
database:
    # Database driver (redis)
    driver: redis
    # Redis Driver Configs
    redis:
        hash_prefix: rabbit_

# Third Party API Integration
integrations:
    # Github Configs
    github:
        # Webhook URI (Full URL will be app.domain + webhook_uri)
        webhook_uri: /webhook/github
        # Webhook Secret (From Repo settings page > Webhooks)
        webhook_secret: ${RABBIT_INTEGRATION_GITHUB_WEBHOOK_SECRET}
        # whether to use ssh or https to clone
        clone_with: ${RABBIT_INTEGRATION_GITHUB_CLONE_WITH:-https}
        # HTTPS URL format, Full name will be something like Clivern/Rabbit
        https_format: https://github.com/{$full_name}.git
        # SSH URL format, Full name will be something like Clivern/Rabbit
        ssh_format: git@github.com:{$full_name}.git
    # Bitbucket Configs
    bitbucket:
        # Webhook URI (Full URL will be app.domain + webhook_uri)
        webhook_uri: /webhook/bitbucket
        # whether to use ssh or https to clone
        clone_with: ${RABBIT_INTEGRATION_BITBUCKET_CLONE_WITH:-https}
        # HTTPS URL format, Full name will be something like Clivern/Rabbit
        https_format: https://bitbucket.org/{$full_name}.git
        # SSH URL format, Full name will be something like Clivern/Rabbit
        ssh_format: git@bitbucket.org:{$full_name}.git
