version: '3'
services:
    redis:
        image: 'redis:5.0.5-alpine'
        volumes:
            - 'rabbit_redis:/data'
        restart: unless-stopped
    rabbit:
        image: 'rabbit:1.0.0'
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - redis
        volumes:
            - '~/.ssh:/root/.ssh'
            - 'rabbit_configs:/app/configs'
            - 'rabbit_var:/app/var'
        restart: unless-stopped

volumes:
    rabbit_redis: null
    rabbit_configs: null
    rabbit_var: null