version: '3'
services:
   redis:
      image: 'redis:5.0.5-alpine'
      volumes:
         - 'redis_data:/data'
      restart: always
   web:
      image: 'docker.pkg.github.com/clivern/rabbit/rabbit:0.1.2'
      command: './rabbit --config /app/configs/config.docker.yml'
      ports:
         - "8080:8080"
      depends_on:
         - redis
      volumes:
         - '~/.ssh:/root/.ssh'
         - './var:/app/var'
         - './configs:/app/configs'
      restart: always
      healthcheck:
         test: './rabbit --config /app/configs/config.docker.yml --exec health'
         interval: 5s
         timeout: 2s
         retries: 5
volumes:
    redis_data: null
